genome_dir: "/path/to/genome_dir"
genome_fasta_file_name: "genome.fa"
tools_dir: "./tools"
tmp: "/path/to/tmp"

fgbio: "/path/to/fgbio"
java: "/path/to/java"
bwameth: "/path/to/bwameth.py"
samtools: "/path/to/samtools"
python3: "/path/to/python3"
picard_path: "/path/to/picard.jar"
