rules:
  call_consensus_reads_molecular:
    xmx: "100g"
    error_rate_pre_umi: 45
    min_consensus_base_quality: 0
    consensus_call_overlapping_bases: "true"
    error_rate_post_umi: 30
    min_input_base_quality: 0
    min_reads: 1
    threads: 20
    others: []

  duplex_metrics:
    threads: 10
    others: []

  consensus_to_fq_unfiltered:
    compression_level: 5
    include_non_pf_reads: "true"
    threads: 5
    others: []

  align_consensus_unfiltered:
    aligner_options: "--read-group-id RG1"
    samtools_options: "-q 20"
    threads: 20
    others: []

  mergeAunA_consensus:
    xmx: "100G"
    sort_memory: "2G"
    validation_stringency: "SILENT"
    threads: 20
    others: []

  mergeAunA_consensus_grepaligned:
    samtools_flags: "-F 4"
    threads: 10
    others: []

  convert_Bstrain:
    threads: 20
    others: []

  extend:
    extend_length: 10
    threads: 10
    others: []

  groupsort_convert:
    xmx: "60G"
    sort_order: "TemplateCoordinate"
    tmp_dir: "tmp"
    threads: 20
    others: []

  callduplex:
    xmx: "100g"
    error_rate_pre_umi: 45
    error_rate_post_umi: 30
    min_input_base_quality: 0
    min_reads: 0
    consensus_overlap_mode: "AGGREGATE"
    threads: 20
    others: []

  align_consensus_unfiltered_duplex:
    aligner_options: "--read-group-id RG2"
    samtools_options: "-q 20"
    threads: 20
    others: []

global:
  tmp_root: "./tmp"
  genome_dir: "/path/to/ref/dir"
  genome_fasta: "fasta_name.fa"
  picard_path: "/opt/picard.jar"
  fgbio_path: "/usr/local/bin/fgbio"
  bwameth_path: "/usr/local/bin/bwameth.py"
  samtools_path: "/usr/bin/samtools"
  python_path: "/usr/bin/python3"
  tools_dir: "./tools"
